// ========== TRADUCCIONES ==========
const translations={es:{wallet:"Wallet",production:"Producción Total",prestigeLevel:"Nivel Prestige",nextPrestige:"Siguiente Prestige",clickMe:"¡Haz Click!",clickPower:"Poder Click",tutorial:"📚 Tutorial",share:"🔗 Compartir",prestige:"🌙 Moon Landing",tabUpgrades:"Upgrades",tabSkins:"Skins",tabMachines:"Máquinas",tabAchievements:"Logros",tabSettings:"Config",upgradesOf:"Mejoras de",skinsOf:"Skins de",machinesTitle:"🏭 Máquinas Disponibles",achievementsTitle:"🏆 Logros",settingsTitle:"⚙️ Configuración",soundLabel:"Sonido",languageLabel:"Idioma",saveBtn:"💾 Guardar",exportBtn:"📤 Exportar",importBtn:"📥 Importar",resetBtn:"🗑️ Reset Total",tutorialTitle:"🎮 Tutorial Interactivo",next:"Siguiente",skip:"Saltar",welcomeBack:"¡Bienvenido de vuelta!",offlineEarnings:"Mientras estabas fuera ganaste:",collect:"Recolectar",buy:"Comprar",unlock:"Desbloquear",unlocked:"Desbloqueada",locked:"Bloqueada",owned:"Tienes",cost:"Costo",activate:"Activar",active:"Activa"},en:{wallet:"Wallet",production:"Total Production",prestigeLevel:"Prestige Level",nextPrestige:"Next Prestige",clickMe:"Click Me!",clickPower:"Click Power",tutorial:"📚 Tutorial",share:"🔗 Share",prestige:"🌙 Moon Landing",tabUpgrades:"Upgrades",tabSkins:"Skins",tabMachines:"Machines",tabAchievements:"Achievements",tabSettings:"Settings",upgradesOf:"Upgrades for",skinsOf:"Skins for",machinesTitle:"🏭 Available Machines",achievementsTitle:"🏆 Achievements",settingsTitle:"⚙️ Settings",soundLabel:"Sound",languageLabel:"Language",saveBtn:"💾 Save",exportBtn:"📤 Export",importBtn:"📥 Import",resetBtn:"🗑️ Hard Reset",tutorialTitle:"🎮 Interactive Tutorial",next:"Next",skip:"Skip",welcomeBack:"Welcome back!",offlineEarnings:"While you were away you earned:",collect:"Collect",buy:"Buy",unlock:"Unlock",unlocked:"Unlocked",locked:"Locked",owned:"Owned",cost:"Cost",activate:"Activate",active:"Active"}};

const machinesData=[{id:'coffee',emoji:'☕',name:{es:'Café',en:'Coffee'},desc:{es:'Tu primera máquina',en:'Your first machine'},unlockCost:0,color:'#ff00ff',baseClickPower:1,unlocked:true},{id:'tea',emoji:'🍵',name:{es:'Té Verde',en:'Green Tea'},desc:{es:'Elegante y refinado',en:'Elegant and refined'},unlockCost:500,color:'#39ff14',baseClickPower:5},{id:'beer',emoji:'🍺',name:{es:'Cerveza',en:'Beer'},desc:{es:'Popular en horas felices',en:'Popular at happy hours'},unlockCost:5000,color:'#ffdd00',baseClickPower:25},{id:'cocktail',emoji:'🍹',name:{es:'Cóctel',en:'Cocktail'},desc:{es:'Exótico y rentable',en:'Exotic and profitable'},unlockCost:50000,color:'#00f0ff',baseClickPower:125},{id:'wine',emoji:'🍷',name:{es:'Vino',en:'Wine'},desc:{es:'Lujo puro',en:'Pure luxury'},unlockCost:500000,color:'#ff0066',baseClickPower:625},{id:'smoothie',emoji:'🥤',name:{es:'Smoothie',en:'Smoothie'},desc:{es:'Saludable y moderno',en:'Healthy and modern'},unlockCost:5000000,color:'#ff6b00',baseClickPower:3125}];

const upgradesData={coffee:[{id:'coffee_auto1',name:{es:'Cafetera Básica',en:'Basic Maker'},baseCost:15,production:0.1},{id:'coffee_auto2',name:{es:'Barista Bot',en:'Barista Bot'},baseCost:100,production:1},{id:'coffee_auto3',name:{es:'Máquina Industrial',en:'Industrial Machine'},baseCost:1000,production:10},{id:'coffee_click',name:{es:'Mejor Grano',en:'Better Bean'},baseCost:50,clickBonus:1},{id:'coffee_multi',name:{es:'Marketing',en:'Marketing'},baseCost:500,multiplier:1.5}],tea:[{id:'tea_auto1',name:{es:'Tetera Auto',en:'Auto Teapot'},baseCost:200,production:2},{id:'tea_auto2',name:{es:'Maestro Té',en:'Tea Master'},baseCost:1500,production:15},{id:'tea_auto3',name:{es:'Plantación',en:'Plantation'},baseCost:10000,production:100},{id:'tea_click',name:{es:'Hojas Premium',en:'Premium Leaves'},baseCost:400,clickBonus:3},{id:'tea_multi',name:{es:'Ceremonia',en:'Ceremony'},baseCost:3000,multiplier:2}],beer:[{id:'beer_auto1',name:{es:'Barril',en:'Barrel'},baseCost:2000,production:20},{id:'beer_auto2',name:{es:'Cervecería',en:'Brewery'},baseCost:12000,production:150},{id:'beer_auto3',name:{es:'Fábrica',en:'Factory'},baseCost:80000,production:1000},{id:'beer_click',name:{es:'Mejor Lúpulo',en:'Better Hops'},baseCost:3000,clickBonus:10},{id:'beer_multi',name:{es:'Happy Hour',en:'Happy Hour'},baseCost:20000,multiplier:2}],cocktail:[{id:'cocktail_auto1',name:{es:'Coctelera',en:'Shaker'},baseCost:20000,production:200},{id:'cocktail_auto2',name:{es:'Bartender Robot',en:'Robot Bartender'},baseCost:120000,production:1500},{id:'cocktail_auto3',name:{es:'Bar Auto',en:'Auto Bar'},baseCost:800000,production:10000},{id:'cocktail_click',name:{es:'Licores Premium',en:'Premium Liquors'},baseCost:30000,clickBonus:50},{id:'cocktail_multi',name:{es:'Tiki Bar',en:'Tiki Bar'},baseCost:200000,multiplier:3}],wine:[{id:'wine_auto1',name:{es:'Bodega',en:'Winery'},baseCost:200000,production:2000},{id:'wine_auto2',name:{es:'Viñedo',en:'Vineyard'},baseCost:1200000,production:15000},{id:'wine_auto3',name:{es:'Château',en:'Château'},baseCost:8000000,production:100000},{id:'wine_click',name:{es:'Añada Especial',en:'Special Vintage'},baseCost:300000,clickBonus:250},{id:'wine_multi',name:{es:'Sommelier',en:'Sommelier'},baseCost:2000000,multiplier:4}],smoothie:[{id:'smoothie_auto1',name:{es:'Licuadora',en:'Blender'},baseCost:2000000,production:20000},{id:'smoothie_auto2',name:{es:'Juice Bar',en:'Juice Bar'},baseCost:12000000,production:150000},{id:'smoothie_auto3',name:{es:'Superfood Factory',en:'Superfood Factory'},baseCost:80000000,production:1000000},{id:'smoothie_click',name:{es:'Superfoods',en:'Superfoods'},baseCost:3000000,clickBonus:1250},{id:'smoothie_multi',name:{es:'Health Trend',en:'Health Trend'},baseCost:20000000,multiplier:5}]};

const skinsData={coffee:[{id:'coffee_default',emoji:'☕',name:{es:'Clásica',en:'Classic'},unlocked:true},{id:'coffee_mug',emoji:'🍵',name:{es:'Taza Grande',en:'Big Mug'},requirement:{type:'upgrade',count:3}},{id:'coffee_thermo',emoji:'🥤',name:{es:'Termo',en:'Thermos'},requirement:{type:'upgrade',count:8}},{id:'coffee_gold',emoji:'🏆',name:{es:'Oro',en:'Gold'},requirement:{type:'upgrade',count:15}}],tea:[{id:'tea_default',emoji:'🍵',name:{es:'Verde',en:'Green'},unlocked:true},{id:'tea_black',emoji:'🫖',name:{es:'Negro',en:'Black'},requirement:{type:'upgrade',count:3}},{id:'tea_herbal',emoji:'🌿',name:{es:'Herbal',en:'Herbal'},requirement:{type:'upgrade',count:8}},{id:'tea_matcha',emoji:'🍃',name:{es:'Matcha',en:'Matcha'},requirement:{type:'upgrade',count:15}}],beer:[{id:'beer_default',emoji:'🍺',name:{es:'Rubia',en:'Blonde'},unlocked:true},{id:'beer_dark',emoji:'🍻',name:{es:'Negra',en:'Dark'},requirement:{type:'upgrade',count:3}},{id:'beer_ipa',emoji:'🍾',name:{es:'IPA',en:'IPA'},requirement:{type:'upgrade',count:8}},{id:'beer_gold',emoji:'🥇',name:{es:'Oro',en:'Gold'},requirement:{type:'upgrade',count:15}}],cocktail:[{id:'cocktail_default',emoji:'🍹',name:{es:'Tropical',en:'Tropical'},unlocked:true},{id:'cocktail_berry',emoji:'🍓',name:{es:'Fresa',en:'Berry'},requirement:{type:'upgrade',count:3}},{id:'cocktail_mint',emoji:'🌿',name:{es:'Menta',en:'Mint'},requirement:{type:'upgrade',count:8}},{id:'cocktail_rainbow',emoji:'🌈',name:{es:'Arcoíris',en:'Rainbow'},requirement:{type:'upgrade',count:15}}],wine:[{id:'wine_default',emoji:'🍷',name:{es:'Tinto',en:'Red'},unlocked:true},{id:'wine_white',emoji:'🥂',name:{es:'Blanco',en:'White'},requirement:{type:'upgrade',count:3}},{id:'wine_rose',emoji:'🌹',name:{es:'Rosé',en:'Rosé'},requirement:{type:'upgrade',count:8}},{id:'wine_champagne',emoji:'🍾',name:{es:'Champagne',en:'Champagne'},requirement:{type:'upgrade',count:15}}],smoothie:[{id:'smoothie_default',emoji:'🥤',name:{es:'Verde',en:'Green'},unlocked:true},{id:'smoothie_berry',emoji:'🫐',name:{es:'Berry',en:'Berry'},requirement:{type:'upgrade',count:3}},{id:'smoothie_tropical',emoji:'🥭',name:{es:'Tropical',en:'Tropical'},requirement:{type:'upgrade',count:8}},{id:'smoothie_protein',emoji:'💪',name:{es:'Protein',en:'Protein'},requirement:{type:'upgrade',count:15}}]};

const achievementsData=[{id:'first100',icon:'🎯',name:{es:'Primer Paso',en:'First Step'},desc:{es:'Gana 100',en:'Earn 100'},check:s=>s.totalEarned>=100,reward:{type:'turbo',level:1}},{id:'unlock3',icon:'🏭',name:{es:'Emprendedor',en:'Entrepreneur'},desc:{es:'Desbloquea 3 máquinas',en:'Unlock 3 machines'},check:s=>Object.values(s.machines).filter(m=>m.unlocked).length>=3},{id:'upgrade20',icon:'⚡',name:{es:'Coleccionista',en:'Collector'},desc:{es:'Compra 20 upgrades',en:'Buy 20 upgrades'},check:s=>{let t=0;Object.values(s.machineUpgrades).forEach(m=>{Object.values(m).forEach(c=>t+=c)});return t>=20},reward:{type:'turbo',level:2}},{id:'firstPrestige',icon:'🌙',name:{es:'Luna Nueva',en:'New Moon'},desc:{es:'Primer prestige',en:'First prestige'},check:s=>s.prestigeLevel>=1,reward:{type:'turbo',level:3}},{id:'unlockAll',icon:'👑',name:{es:'Rey del Negocio',en:'Business King'},desc:{es:'Desbloquea todas',en:'Unlock all'},check:s=>Object.values(s.machines).every(m=>m.unlocked)},{id:'prestige5',icon:'🚀',name:{es:'Veterano',en:'Veteran'},desc:{es:'Prestige 5',en:'Prestige 5'},check:s=>s.prestigeLevel>=5}];

const tutorialSteps=[{es:'1️⃣ Haz click en ☕ para ganar',en:'1️⃣ Click on ☕ to earn'},{es:'2️⃣ Compra upgrades en ⚡',en:'2️⃣ Buy upgrades in ⚡'},{es:'3️⃣ Desbloquea máquinas en 🏭',en:'3️⃣ Unlock machines in 🏭'},{es:'4️⃣ Cambia entre máquinas',en:'4️⃣ Switch between machines'},{es:'5️⃣ Desbloquea skins en 🎨',en:'5️⃣ Unlock skins in 🎨'},{es:'6️⃣ Haz Moon Landing 🌙',en:'6️⃣ Do Moon Landing 🌙'}];

let gameState={wallet:0,totalEarned:0,totalClicks:0,prestigeLevel:0,prestigeGoal:10000,prestigeMultiplier:1,currentMachine:'coffee',machines:{},machineUpgrades:{},machineSkins:{},turboUnlocked:0,turboActive:false,turboEndTime:0,turboCooldownEnd:0,achievements:{},settings:{sound:true,lang:'es'},lastSaveTime:Date.now()};

let currentLang='es',currentTutorialStep=0,lastTick=Date.now();function init(){loadGame();initializeMachines();currentLang=gameState.settings.lang;updateLang();setupEventListeners();startGameLoop();checkFirstTime();checkOfflineEarnings();renderMachinesRow();renderMachinesList();renderAchievements();switchMachine(gameState.currentMachine);updateUI()}

function initializeMachines(){machinesData.forEach(m=>{if(!gameState.machines[m.id])gameState.machines[m.id]={unlocked:m.unlocked||false,production:0,clickPower:m.baseClickPower,activeSkin:`${m.id}_default`};if(!gameState.machineUpgrades[m.id])gameState.machineUpgrades[m.id]={};if(!gameState.machineSkins[m.id])gameState.machineSkins[m.id]={[`${m.id}_default`]:true}})}

function saveGame(show=false){gameState.lastSaveTime=Date.now();localStorage.setItem('cryptoCafeSave',JSON.stringify(gameState));if(show)showToast(currentLang==='es'?'¡Guardado!':'Saved!')}

function loadGame(){const s=localStorage.getItem('cryptoCafeSave');if(s){try{gameState={...gameState,...JSON.parse(s)}}catch(e){console.error(e)}}}

function exportSave(){navigator.clipboard.writeText(JSON.stringify(gameState));showToast('¡Copiado!')}

function importSave(){const s=prompt('Pega tu guardado:');if(s){try{gameState=JSON.parse(s);saveGame(true);location.reload()}catch(e){alert('Inválido')}}}

function resetGame(){if(confirm('¿Seguro? Perderás TODO')){localStorage.clear();location.reload()}}

function checkOfflineEarnings(){const now=Date.now(),diff=(now-gameState.lastSaveTime)/1000;if(diff>60){const time=Math.min(diff,28800),prod=calculateTotalProduction(),earn=Math.floor(prod*time*0.5);if(earn>0){gameState.wallet+=earn;document.getElementById('offlineAmount').textContent=formatNumber(earn);showModal('offlineModal')}}}

function checkFirstTime(){if(!localStorage.getItem('cryptoCafeFirstTime')){localStorage.setItem('cryptoCafeFirstTime','true');setTimeout(()=>showTutorial(),500)}}

function showTutorial(){currentTutorialStep=0;renderTutorial();showModal('tutorialModal')}

function renderTutorial(){document.getElementById('tutorialSteps').innerHTML=tutorialSteps.map((s,i)=>`<div class="tutorial-step ${i===currentTutorialStep?'active':''} ${i<currentTutorialStep?'completed':''}">${s[currentLang]}</div>`).join('')}

function nextTutorialStep(){currentTutorialStep++;if(currentTutorialStep>=tutorialSteps.length)closeModal('tutorialModal');else renderTutorial()}

function switchMachine(id){if(!gameState.machines[id]||!gameState.machines[id].unlocked)return;gameState.currentMachine=id;const m=machinesData.find(x=>x.id===id),skin=gameState.machines[id].activeSkin,sd=skinsData[id].find(s=>s.id===skin);document.getElementById('machineEmoji').textContent=sd.emoji;document.getElementById('machineName').textContent=m.emoji+' '+m.name[currentLang];document.documentElement.style.setProperty('--neon-magenta',m.color);renderMachinesRow();renderUpgrades();renderSkins();updateUI()}

function renderMachinesRow(){document.getElementById('machinesRow').innerHTML=machinesData.map(m=>{const u=gameState.machines[m.id].unlocked,a=gameState.currentMachine===m.id;return`<div class="machine-icon ${a?'active':''} ${!u?'locked':''}" onclick="${u?`switchMachine('${m.id}')`:''}">${u?m.emoji:'🔒'}${!u?`<div class="machine-lock-badge">${formatNumber(m.unlockCost)}</div>`:''}</div>`}).join('')}

function renderMachinesList(){document.getElementById('machinesList').innerHTML=machinesData.map(m=>{const u=gameState.machines[m.id].unlocked,c=gameState.wallet>=m.unlockCost;return`<div class="machine-card ${u?'unlocked':'locked'}"><div class="machine-card-info"><div class="machine-card-icon">${m.emoji}</div><div class="machine-card-name">${m.name[currentLang]}</div><div class="machine-card-desc">${m.desc[currentLang]}</div><div class="machine-card-stats"><span>Click: +${m.baseClickPower}</span>${u?`<span style="color:var(--neon-green);">✓ ${translations[currentLang].unlocked}</span>`:''}</div></div><button class="machine-unlock-btn" onclick="unlockMachine('${m.id}')" ${u||!c?'disabled':''}>${u?'✓ '+translations[currentLang].unlocked:translations[currentLang].unlock+' '+formatNumber(m.unlockCost)}</button></div>`}).join('')}

function unlockMachine(id){const m=machinesData.find(x=>x.id===id);if(gameState.wallet>=m.unlockCost&&!gameState.machines[id].unlocked){gameState.wallet-=m.unlockCost;gameState.machines[id].unlocked=true;renderMachinesRow();renderMachinesList();showToast(`🎉 ${m.name[currentLang]}!`);checkAchievements()}}

function clickMachine(e){const m=gameState.machines[gameState.currentMachine],val=m.clickPower*gameState.prestigeMultiplier*(gameState.turboActive?5:1);gameState.wallet+=val;gameState.totalClicks++;gameState.totalEarned+=val;createSteam(e.clientX,e.clientY);createFloatingNumber(e.clientX,e.clientY,`+${formatNumber(val)}`);updateUI();checkAchievements()}

function createSteam(x,y){for(let i=0;i<5;i++){const p=document.createElement('div');p.className='steam-particle';p.textContent='💨';p.style.left=`${x+(Math.random()-0.5)*40}px`;p.style.top=`${y}px`;document.getElementById('particles').appendChild(p);setTimeout(()=>p.remove(),1000)}}

function createFloatingNumber(x,y,t){const n=document.createElement('div');n.className='steam-particle';n.style.left=`${x}px`;n.style.top=`${y-30}px`;n.style.color='var(--neon-yellow)';n.style.fontSize='1.5rem';n.style.fontWeight='bold';n.textContent=t;document.getElementById('particles').appendChild(n);setTimeout(()=>n.remove(),1000)}

function renderUpgrades(){const mid=gameState.currentMachine,md=machinesData.find(m=>m.id===mid),ups=upgradesData[mid];document.getElementById('upgradesTitle').textContent=`⚡ ${translations[currentLang].upgradesOf} ${md.name[currentLang]}`;document.getElementById('upgradesList').innerHTML=ups.map(u=>{const own=gameState.machineUpgrades[mid][u.id]||0,cost=Math.floor(u.baseCost*Math.pow(1.15,own)),can=gameState.wallet>=cost;let eff='';if(u.production)eff=`+${u.production}/s`;if(u.multiplier)eff=`×${u.multiplier}`;if(u.clickBonus)eff=`+${u.clickBonus}`;return`<div class="upgrade-card"><div class="upgrade-info"><div class="upgrade-name">${u.name[currentLang]}</div><div class="upgrade-stats"><span>${translations[currentLang].owned}: ${own}</span><span>${eff}</span></div></div><button class="upgrade-buy" data-upgrade-id="${u.id}" ${!can?'disabled':''}>${translations[currentLang].buy}<br>${formatNumber(cost)}</button></div>`}).join('');document.querySelectorAll('.upgrade-buy').forEach(b=>b.addEventListener('click',()=>buyUpgrade(b.getAttribute('data-upgrade-id'))))}

function updateUpgradeButtons(){const mid=gameState.currentMachine,ups=upgradesData[mid];document.querySelectorAll('.upgrade-buy').forEach(b=>{const uid=b.getAttribute('data-upgrade-id'),u=ups.find(x=>x.id===uid);if(!u)return;const own=gameState.machineUpgrades[mid][uid]||0,cost=Math.floor(u.baseCost*Math.pow(1.15,own)),can=gameState.wallet>=cost;b.disabled=!can;b.innerHTML=`${translations[currentLang].buy}<br>${formatNumber(cost)}`})}

function buyUpgrade(uid){const mid=gameState.currentMachine,u=upgradesData[mid].find(x=>x.id===uid),own=gameState.machineUpgrades[mid][uid]||0,cost=Math.floor(u.baseCost*Math.pow(1.15,own));if(gameState.wallet>=cost){gameState.wallet-=cost;gameState.machineUpgrades[mid][uid]=own+1;recalculateMachineStats(mid);checkSkinUnlocks(mid);renderUpgrades();renderSkins();updateUI();showToast(`✅ ${u.name[currentLang]}!`);checkAchievements()}}

function recalculateMachineStats(id){const md=machinesData.find(m=>m.id===id),ups=upgradesData[id];let prod=0,click=md.baseClickPower,multi=1;ups.forEach(u=>{const own=gameState.machineUpgrades[id][u.id]||0;if(own>0){if(u.production)prod+=u.production*own;if(u.clickBonus)click+=u.clickBonus*own;if(u.multiplier)multi*=Math.pow(u.multiplier,own)}});gameState.machines[id].production=prod*multi;gameState.machines[id].clickPower=click}

function calculateTotalProduction(){let t=0;Object.keys(gameState.machines).forEach(id=>{if(gameState.machines[id].unlocked)t+=gameState.machines[id].production});return t*gameState.prestigeMultiplier}

function renderSkins(){const mid=gameState.currentMachine,md=machinesData.find(m=>m.id===mid),sks=skinsData[mid];document.getElementById('skinsTitle').textContent=`🎨 ${translations[currentLang].skinsOf} ${md.name[currentLang]}`;document.getElementById('skinsList').innerHTML=sks.map(s=>{const u=gameState.machineSkins[mid][s.id]||false,a=gameState.machines[mid].activeSkin===s.id;return`<div class="skin-card ${a?'active':''} ${!u?'locked':''}" onclick="${u?`applySkin('${s.id}')`:''}""><div class="skin-emoji">${u?s.emoji:'🔒'}</div><div>${s.name[currentLang]}</div>${a?`<div style="color:var(--neon-green);margin-top:5px;">✓</div>`:''}</div>`}).join('')}

function checkSkinUnlocks(id){const sks=skinsData[id],tot=Object.values(gameState.machineUpgrades[id]).reduce((a,b)=>a+b,0);sks.forEach(s=>{if(s.requirement&&s.requirement.type==='upgrade'){if(tot>=s.requirement.count){if(!gameState.machineSkins[id][s.id]){gameState.machineSkins[id][s.id]=true;showToast(`🎨 ${s.name[currentLang]}!`)}}}})}

function applySkin(sid){const mid=gameState.currentMachine;gameState.machines[mid].activeSkin=sid;const s=skinsData[mid].find(x=>x.id===sid);document.getElementById('machineEmoji').textContent=s.emoji;renderSkins();showToast(`✨ ${s.name[currentLang]}`)}

function renderAchievements(){document.getElementById('achievementsList').innerHTML=achievementsData.map(a=>{const u=gameState.achievements[a.id]||false;return`<div class="achievement-card ${u?'unlocked':''}"><div class="achievement-icon">${a.icon}</div><div class="achievement-name">${a.name[currentLang]}</div><div class="achievement-desc">${a.desc[currentLang]}</div><div style="margin-top:10px;font-weight:bold;color:${u?'var(--neon-green)':'var(--text-secondary)'};">${u?'✓':translations[currentLang].locked}</div></div>`}).join('')}

function checkAchievements(){achievementsData.forEach(a=>{if(!gameState.achievements[a.id]&&a.check(gameState)){gameState.achievements[a.id]=true;showToast(`🏆 ${a.name[currentLang]}!`);if(a.reward&&a.reward.type==='turbo'){gameState.turboUnlocked=Math.max(gameState.turboUnlocked,a.reward.level);document.getElementById('turboBtn').style.display='inline-block';showToast('⚡ Turbo!')}renderAchievements()}})}

function activateTurbo(){const now=Date.now();if(now<gameState.turboCooldownEnd){showToast('⏳ Cooldown');return}if(gameState.turboActive)return;gameState.turboActive=true;gameState.turboEndTime=now+30000;showToast('⚡ Turbo ×5!')}

function updateTurboButton(){if(gameState.turboUnlocked===0)return;const btn=document.getElementById('turboBtn'),now=Date.now();if(gameState.turboActive){const r=Math.ceil((gameState.turboEndTime-now)/1000);btn.innerHTML=`⚡ ${r}s`;btn.disabled=true;btn.style.opacity='0.7'}else if(now<gameState.turboCooldownEnd){const r=Math.ceil((gameState.turboCooldownEnd-now)/1000);btn.innerHTML=`⏳ ${r}s`;btn.disabled=true;btn.style.opacity='0.5'}else{btn.innerHTML='⚡ Turbo';btn.disabled=false;btn.style.opacity='1'}}

function doPrestige(){if(gameState.wallet>=gameState.prestigeGoal){if(confirm('¿Moon Landing? +20% producción')){gameState.wallet=0;gameState.prestigeLevel++;gameState.prestigeMultiplier=1+(gameState.prestigeLevel*0.2);gameState.prestigeGoal*=10;Object.keys(gameState.machines).forEach(id=>{if(id!=='coffee')gameState.machines[id].unlocked=false;gameState.machines[id].production=0;gameState.machines[id].clickPower=machinesData.find(m=>m.id===id).baseClickPower;gameState.machines[id].activeSkin=`${id}_default`});Object.keys(gameState.machineUpgrades).forEach(id=>{gameState.machineUpgrades[id]={}});Object.keys(gameState.machineSkins).forEach(id=>{gameState.machineSkins[id]={[`${id}_default`]:true}});gameState.currentMachine='coffee';renderMachinesRow();renderMachinesList();renderUpgrades();renderSkins();updateUI();switchMachine('coffee');showToast(`🌙 Prestige ${gameState.prestigeLevel}!`);checkAchievements()}}}

function startGameLoop(){setInterval(()=>{const now=Date.now(),delta=(now-lastTick)/1000,prod=calculateTotalProduction()*(gameState.turboActive?5:1);gameState.wallet+=prod*delta;gameState.totalEarned+=prod*delta;if(gameState.turboActive&&now>=gameState.turboEndTime){gameState.turboActive=false;gameState.turboCooldownEnd=now+60000;showToast('⚡ Turbo fin')}lastTick=now;updateUI();updateUpgradeButtons();updateTurboButton()},100);setInterval(()=>saveGame(false),10000)}

function updateUI(){const tot=calculateTotalProduction()*(gameState.turboActive?5:1),cm=gameState.machines[gameState.currentMachine],ccp=cm.clickPower*gameState.prestigeMultiplier*(gameState.turboActive?5:1),cpr=cm.production*gameState.prestigeMultiplier*(gameState.turboActive?5:1);document.getElementById('walletDisplay').textContent=formatNumber(gameState.wallet);document.getElementById('productionDisplay').textContent=formatNumber(tot)+'/s';document.getElementById('prestigeLevelDisplay').textContent=gameState.prestigeLevel;document.getElementById('prestigeGoalDisplay').textContent=formatNumber(gameState.prestigeGoal);document.getElementById('currentClickPower').textContent=formatNumber(ccp);document.getElementById('currentMachineProduction').textContent=formatNumber(cpr)+'/s';document.getElementById('prestigeBtn').disabled=gameState.wallet<gameState.prestigeGoal}

function formatNumber(n){if(n>=1e12)return(n/1e12).toFixed(2)+'T';if(n>=1e9)return(n/1e9).toFixed(2)+'B';if(n>=1e6)return(n/1e6).toFixed(2)+'M';if(n>=1e3)return(n/1e3).toFixed(2)+'K';return Math.floor(n).toString()}

function updateLang(){document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.getAttribute('data-i18n');if(translations[currentLang][k])el.textContent=translations[currentLang][k]});document.getElementById('langToggle').textContent=currentLang.toUpperCase();if(gameState.currentMachine){renderMachinesList();renderUpgrades();renderSkins();renderAchievements()}}

function toggleLang(){gameState.settings.lang=currentLang==='es'?'en':'es';currentLang=gameState.settings.lang;updateLang();saveGame(false)}

function showModal(id){document.getElementById(id).classList.add('active')}
function closeModal(id){document.getElementById(id).classList.remove('active')}

function showToast(msg){const t=document.createElement('div');t.className='toast';t.textContent=msg;document.getElementById('toastContainer').appendChild(t);setTimeout(()=>t.remove(),3000)}

function switchTab(tab){document.querySelectorAll('.tab-btn').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.remove('active'));event.target.classList.add('active');document.getElementById(tab).classList.add('active')}

function setupEventListeners(){document.getElementById('espressoMachine').addEventListener('click',clickMachine);document.getElementById('tutorialBtn').addEventListener('click',showTutorial);document.getElementById('turboBtn').addEventListener('click',activateTurbo);document.getElementById('prestigeBtn').addEventListener('click',doPrestige);document.getElementById('shareBtn').addEventListener('click',()=>{navigator.clipboard.writeText(`CryptoCafe! ${formatNumber(gameState.wallet)} Prestige ${gameState.prestigeLevel}`);showToast('¡Copiado!')});document.getElementById('tutorialNextBtn').addEventListener('click',nextTutorialStep);document.getElementById('tutorialSkipBtn').addEventListener('click',()=>closeModal('tutorialModal'));document.getElementById('offlineCloseBtn').addEventListener('click',()=>closeModal('offlineModal'));document.getElementById('soundToggle').addEventListener('click',function(){gameState.settings.sound=!gameState.settings.sound;this.textContent=gameState.settings.sound?'ON':'OFF'});document.getElementById('langToggle').addEventListener('click',toggleLang);document.getElementById('saveBtn').addEventListener('click',()=>saveGame(true));document.getElementById('exportBtn').addEventListener('click',exportSave);document.getElementById('importBtn').addEventListener('click',importSave);document.getElementById('resetBtn').addEventListener('click',resetGame);document.querySelectorAll('.tab-btn').forEach(b=>b.addEventListener('click',()=>switchTab(b.getAttribute('data-tab'))))}

window.addEventListener('DOMContentLoaded',init);